### ISSUE TITLE
DELL P2418D 

### ISSUE THREAD

**Issue by DeTeKe** [lihaoyun6/macOS-Displays-icon#16]
不怎么会用PS不知道怎么添加阴影 图修的有问题 边缘有白点

![QQ20190611-133626](https://user-images.githubusercontent.com/6011145/59246140-0625f780-8c4e-11e9-8a60-31c461b6820d.jpg)

[归档.zip](https://github.com/lihaoyun6/macOS-Displays-icon/files/3274906/default.zip)

**Comment by lihaoyun6** [comment]
已添加DELL P2418D
