### ISSUE TITLE
U2417H

### ISSUE THREAD

**Issue by webhappyboy070** [lihaoyun6/macOS-Displays-icon#18]
[40e7.pdf](https://github.com/lihaoyun6/macOS-Displays-icon/files/3579980/40e7.pdf)

**Comment by lihaoyun6** [comment]
此图标已经存在了.
This icon already exists.

**Comment by webhappyboy070** [comment]
目前10.4.6beta失效，不知道什么原因，提示成功后重启电脑没效果发自我的iPhone------------------ Original ------------------From: lihaoyun6  <notifications@github.com>Date: Fri,Sep 6,2019 5:07 PMTo: lihaoyun6/macOS-Displays-icon <macOS-Displays-icon@noreply.github.com>Cc: webhappyboy070 <webhappyboy070@gmail.com>, Author <author@noreply.github.com>Subject: Re: [lihaoyun6/macOS-Displays-icon] U2417H (#18)此图标已经存在了.
This icon already exists.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lihaoyun6/macOS-Displays-icon/issues/18?email_source=notifications\u0026email_token=AEMWQAOT2X73V2E43D54FALQIIMW5A5CNFSM4IT7FXP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6CH4EQ#issuecomment-528776722",
"url": "https://github.com/lihaoyun6/macOS-Displays-icon/issues/18?email_source=notifications\u0026email_token=AEMWQAOT2X73V2E43D54FALQIIMW5A5CNFSM4IT7FXP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6CH4EQ#issuecomment-528776722",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
